version: '3'
services:
  app:
    build: .
    volumes:
    - ./app/main.py:/app/main.py
    - ./conf:/conf
    environment:
      - NGINX_HTTP_PORT_NUMBER=1001
      - NGINX_HTTPS_PORT_NUMBER=1002
    ports:
      - 8080:80

  mysql:
    image: mysql:5.7
    container_name: 'mysql'
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'pass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - "3306:3306"
