version: '3'
services:
  app:
    build: .
    volumes:
    - ./app/main.py:/app/main.py
    - ./conf:/conf
    ports:
      - 8080:80

  localstack:
    container_name: s3
    image: localstack/localstack:0.11.1
    ports:
      - "4566-4599:4566-4599"
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=not
      - AWS_SECRET_ACCESS_KEY=real
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=./localstack/data

#    volumes:
#      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"

#  mysql:
#    image: mysql:5.7
#    container_name: 'mysql'
#    environment:
#      MYSQL_DATABASE: 'db'
#      # So you don't have to use root, but you can if you like
#      MYSQL_USER: 'user'
#      # You can use whatever password you like
#      MYSQL_PASSWORD: 'pass'
#      # Password for root access
#      MYSQL_ROOT_PASSWORD: 'pass'
#    ports:
#      - "3306:3306"
